runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /temperature-total-query
  script: unused
  login: optional
  secure: optional
- url: /delete-task
  script: unused
  login: optional
  secure: optional
- url: /landmark-info
  script: unused
  login: optional
  secure: optional
- url: /my-data-url
  script: unused
  login: optional
  secure: optional
- url: /latitude-total-query
  script: unused
  login: optional
  secure: optional
- url: /landmarks
  script: unused
  login: optional
  secure: optional
- url: /list-tasks
  script: unused
  login: optional
  secure: optional
- url: /latitude-query
  script: unused
  login: optional
  secure: optional
- url: /sentiment
  script: unused
  login: optional
  secure: optional
- url: /new-task
  script: unused
  login: optional
  secure: optional
- url: /temperature-query
  script: unused
  login: optional
  secure: optional
